### ISSUE TITLE
Print Queue Monitoring Powershell -> Teams

### ISSUE THREAD

**Issue by kayvanaarssen** [PaoloFrigo/scriptinglibrary#4]
Hi,

Would you be willing to build a Script to monitor print queue from a Print Server.
Like if the Queue is higher than threshold 100 for example.
Send a notification to teams with the Printserver Name | Printer Name (That has the high queue) / current queue size

Also include if a printer is in error state for longer than maybe 10 min? Or some options like that

Just like your Advanced AD Lockout script that would be really awesome!

**Comment by PaoloFrigo** [comment]
Hi Kay,
  Thanks for raising this request. I will work on this in a separate repository. 
Regards
